In [1]:
import torch

# Initializing a Tensor

### Directly from data

In [2]:
a = [1, 2, 3.]
type(a)

list

In [3]:
b = torch.tensor(a)
b

tensor([1., 2., 3.])

In [4]:
type(b)

torch.Tensor

In [5]:
b.dtype

torch.float32

### From a NumPy array

In [6]:
import numpy as np

In [7]:
a = np.random.normal((2,3))
torch.tensor(a)

tensor([1.6818, 3.7554], dtype=torch.float64)

### From another tensor

In [8]:
b = torch.tensor(a)
b

tensor([1.6818, 3.7554], dtype=torch.float64)

In [9]:
c = torch.ones_like(b)
c

tensor([1., 1.], dtype=torch.float64)

In [10]:
c = torch.zeros_like(b)
c

tensor([0., 0.], dtype=torch.float64)

In [11]:
c = torch.rand_like(b)
c

tensor([0.4151, 0.5529], dtype=torch.float64)

### With random or constant values

In [12]:
torch.rand((2,2))

tensor([[0.8619, 0.1921],
        [0.9098, 0.1931]])

In [13]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

# Attributes of a Tensor

In [15]:
a = torch.rand((2,2))

In [16]:
a.dtype

torch.float32

In [17]:
a.shape

torch.Size([2, 2])

In [18]:
a.device

device(type='cpu')

# Operations on Tensors

In [19]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

### Common operations

In [20]:
# Returns True if obj is a PyTorch tensor.
torch.is_tensor(a)

True

In [ ]:
# Returns True if the data type of input is a complex data type.
torch.is_complex(input)
# Returns True if the data type of input is a floating point data type.
torch.is_floating_point(input)

In [21]:
# Returns True if the input is a single element tensor which is not equal to zero after type conversions.
a = torch.tensor(1.0)
torch.is_nonzero(a)

True

In [22]:
a = torch.tensor(0)
torch.is_nonzero(a)

False

In [23]:
# Returns the total number of elements in the input tensor.
a = torch.rand((2,2))
torch.numel(a)

4

In [ ]:
# Constructs a tensor with data.
torch.tensor()
# Convert the data into a torch.Tensor.
torch.as_tensor()
# Creates a Tensor from a numpy.ndarray.
torch.from_numpy()

In [24]:
# Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument size.
torch.zeros((5,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [25]:
torch.zeros((5,5), dtype = torch.int32)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [ ]:
# Returns a tensor filled with the scalar value 0, with the same size as input.
torch.zeros_like()

In [ ]:
# Returns a tensor filled with the scalar value 1, with the shape defined by the variable argument size.
torch.ones()
# Returns a tensor filled with the scalar value 1, with the same size as input.
torch.ones_like()

In [26]:
# Returns a 1-D tensor of size [(end-start)/step] with values from the interval [start, end) taken with common difference step 
# beginning from start.
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [27]:
torch.arange(0,5,2)

tensor([0, 2, 4])

In [28]:
# Returns a 1-D tensor of size [(end-start)/step]+1 with values from start to end with step step.
torch.range(0,5)

D:\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  


tensor([0., 1., 2., 3., 4., 5.])

In [29]:
for i in torch.arange(10):
    print("epoch:", i)

epoch: tensor(0)
epoch: tensor(1)
epoch: tensor(2)
epoch: tensor(3)
epoch: tensor(4)
epoch: tensor(5)
epoch: tensor(6)
epoch: tensor(7)
epoch: tensor(8)
epoch: tensor(9)


In [ ]:
# Creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end, inclusive.
torch.linspace()
# Creates a one-dimensional tensor of size steps whose values are evenly spaced from base^start to base^end, inclusive, 
# on a logarithmic scale with base base.
torch.logspace()

In [30]:
# Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [31]:
# Creates a tensor of size size filled with fill_value.
torch.full((2,2), 5)

tensor([[5, 5],
        [5, 5]])

In [ ]:
# Returns a tensor with the same size as input filled with full_value.
torch.full_like()

In [32]:
# Concatenates the givensequence of seq tensors in the given dimension.
a = torch.rand((2,2))
b = torch.rand((2,3))
torch.cat([a,b], dim = 1)

tensor([[0.2401, 0.3085, 0.4874, 0.6228, 0.3093],
        [0.8638, 0.0114, 0.7772, 0.3000, 0.5600]])

In [33]:
a = torch.rand((2,2))
b = torch.rand((3,2))
torch.cat([a,b], dim = 0)

tensor([[0.6033, 0.1184],
        [0.0782, 0.4179],
        [0.2906, 0.9037],
        [0.7558, 0.7895],
        [0.3575, 0.6883]])

In [34]:
# Splits a tensor into a specific number of chunks. Each chunk is a view of the input tensor.
b = torch.rand((3,2))
b

tensor([[0.6687, 0.8930],
        [0.0348, 0.6988],
        [0.6316, 0.2493]])

In [35]:
torch.chunk(b, chunks = 2)

(tensor([[0.6687, 0.8930],
         [0.0348, 0.6988]]),
 tensor([[0.6316, 0.2493]]))

In [36]:
c, d = torch.chunk(b, chunks = 2)
c

tensor([[0.6687, 0.8930],
        [0.0348, 0.6988]])

In [37]:
d

tensor([[0.6316, 0.2493]])

In [38]:
c, d = torch.chunk(b, chunks = 2, dim = 1)
c

tensor([[0.6687],
        [0.0348],
        [0.6316]])

In [39]:
d

tensor([[0.8930],
        [0.6988],
        [0.2493]])

In [ ]:
# Splits input, a tensor with three or more dimensions, into multiple tensors depthwise according to indices_or_sections.
torch.dsplit()
# Splits input, a tensor with three or more dimensions, into multiple tensors horizontally according to indices_or_sections.
torch.hsplit()

In [ ]:
# Stack tensors in sequence depthwise (along third axis).
torch.dstack()
# Stack tensors in sequence horizontally (column wise).
torch.hstack()

In [40]:
# Gathers values along an axis specified by dim.
t = torch.tensor([[1, 2], [3, 4]])
torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 1],
        [4, 3]])

In [41]:
# Returns a tensor with the same data and number of elements as input, but with the specified shape.
a = torch.arange(4.)
torch.reshape(a, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

In [42]:
b = torch.tensor([[0, 1], [2, 3]])
torch.reshape(b, (-1,))

tensor([0, 1, 2, 3])

In [43]:
# Splits the tensor into chunks. Each chunk is a view of the original tensor.
a = torch.arange(10).reshape(5,2)
torch.split(a, 2)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

In [44]:
torch.split(a, [1, 4])

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

In [46]:
# Returns a tensor with all the dimensions of input of size 1 removed.
b = torch.rand((3,2))
torch.reshape(b, [3, 1, 2])

tensor([[[0.7157, 0.4040]],

        [[0.6535, 0.2760]],

        [[0.3196, 0.9965]]])

In [47]:
torch.squeeze(torch.reshape(b, [3, 1, 2]))

tensor([[0.7157, 0.4040],
        [0.6535, 0.2760],
        [0.3196, 0.9965]])

In [48]:
torch.reshape(b, [3, 1, 2, 1, 1])

tensor([[[[[0.7157]],

          [[0.4040]]]],



        [[[[0.6535]],

          [[0.2760]]]],



        [[[[0.3196]],

          [[0.9965]]]]])

In [49]:
torch.squeeze(torch.reshape(b, [3, 1, 2, 1, 1]), dim = 1).shape

torch.Size([3, 2, 1, 1])

In [50]:
# Concatenates a sequence of tensor along a new dimension.
a = torch.rand((3, 2))
b = torch.rand((3, 2))
torch.stack([a, b])

tensor([[[0.1510, 0.0284],
         [0.8671, 0.4242],
         [0.3242, 0.9166]],

        [[0.5123, 0.8859],
         [0.7947, 0.6811],
         [0.9421, 0.1302]]])

In [51]:
torch.stack([a, b]).shape

torch.Size([2, 3, 2])

In [52]:
torch.stack([a, b], dim = 1).shape

torch.Size([3, 2, 2])

In [53]:
# Returns a new tensor with the elements of input at the given indices.
a = torch.tensor([[4, 3, 5], [6, 7, 8]])
torch.take(a, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

In [54]:
# Constructs a tensor by repeating the elements of input.
a = torch.tensor([1, 2, 3])
a.tile((2,))

tensor([1, 2, 3, 1, 2, 3])

In [55]:
b = torch.tensor([[1, 2], [3, 4]])
torch.tile(b, (2, 2))

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

In [56]:
# Returns a tensor that is a transposed version of input.
a = torch.rand((4, 3))
torch.transpose(a, 0, 1)

tensor([[0.2425, 0.6127, 0.7295, 0.5862],
        [0.5661, 0.1291, 0.0928, 0.0497],
        [0.5581, 0.3105, 0.6799, 0.8418]])

In [57]:
# Removes a tensor dimension.
torch.unbind(a)

(tensor([0.2425, 0.5661, 0.5581]),
 tensor([0.6127, 0.1291, 0.3105]),
 tensor([0.7295, 0.0928, 0.6799]),
 tensor([0.5862, 0.0497, 0.8418]))

In [58]:
torch.unbind(a, dim = 1)

(tensor([0.2425, 0.6127, 0.7295, 0.5862]),
 tensor([0.5661, 0.1291, 0.0928, 0.0497]),
 tensor([0.5581, 0.3105, 0.6799, 0.8418]))

In [59]:
# Returns a new tensor with a dimension of size one inserted at the specified position.
torch.unsqueeze(a, dim = 0)

tensor([[[0.2425, 0.5661, 0.5581],
         [0.6127, 0.1291, 0.3105],
         [0.7295, 0.0928, 0.6799],
         [0.5862, 0.0497, 0.8418]]])

In [63]:
# Returns a tensor of elements selected from either x or y, depending on condition.
a = torch.randn(3, 2)
b = torch.ones(3, 2)
a

tensor([[ 0.5827,  1.0006],
        [-2.2456,  0.1847],
        [ 0.6568,  0.5227]])

In [64]:
torch.where(a > 0, a, b)

tensor([[0.5827, 1.0006],
        [1.0000, 0.1847],
        [0.6568, 0.5227]])

In [ ]:
# Sets the seed for generating random numbers.
torch.manual_seed(seed)

In [ ]:
# Draws binary random numbers (0 or 1) from a Bernoulli distribution.
torch.bernoulli()

In [ ]:
# Returns a tensor of random numbers drawun from separate normal distributions whose mean and standard deviation are given.
torch.normal()

In [ ]:
# Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1).
torch.rand()
# Returns a tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive).
torch.randint()
# Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1.
torch.randn()

In [ ]:
# Returns a random permutation of integers from 0 to n-1.
torch.randperm()