In [1]:
import torch

# Initializing a Tensor

### Directly from data

In [2]:
a = [1, 2, 3.]
type(a)

list

In [3]:
b = torch.tensor(a)
b

tensor([1., 2., 3.])

In [4]:
type(b)

torch.Tensor

In [5]:
b.dtype

torch.float32

### From a NumPy array

In [6]:
import numpy as np

In [7]:
a = np.random.normal((2,3))
torch.tensor(a)

tensor([2.4876, 1.9630], dtype=torch.float64)

### From another tensor

In [8]:
b = torch.tensor(a)
b

tensor([2.4876, 1.9630], dtype=torch.float64)

In [10]:
c = torch.ones_like(b)
c

tensor([1., 1.], dtype=torch.float64)

In [11]:
c = torch.zeros_like(b)
c

tensor([0., 0.], dtype=torch.float64)

In [12]:
c = torch.rand_like(b)
c

tensor([0.7400, 0.6124], dtype=torch.float64)

### With random or constant values

In [13]:
torch.rand((2,2))

tensor([[0.3477, 0.2990],
        [0.8296, 0.2868]])

In [14]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

# Attributes of a Tensor

In [16]:
a = torch.rand((2,2))

In [17]:
a.dtype

torch.float32

In [18]:
a.shape

torch.Size([2, 2])

In [19]:
a.device

device(type='cpu')

# Operations on Tensors

In [20]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

### Common operations

In [21]:
# Returns True if obj is a PyTorch tensor.
torch.is_tensor(a)

True

In [ ]:
# Returns True if the data type of input is a complex data type.
torch.is_complex(input)
# Returns True if the data type of input is a floating point data type.
torch.is_floating_point(input)

In [22]:
# Returns True if the input is a single element tensor which is not equal to zero after type conversions.
a = torch.tensor(1.0)
torch.is_nonzero(a)

True

In [23]:
a = torch.tensor(0)
torch.is_nonzero(a)

False

In [24]:
# Returns the total number of elements in the input tensor.
a = torch.rand((2,2))
torch.numel(a)

4

In [ ]:
# Constructs a tensor with data.
torch.tensor()
# Convert the data into a torch.Tensor.
torch.as_tensor()
# Creates a Tensor from a numpy.ndarray.
torch.from_numpy()

In [25]:
# Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument size.
torch.zeros((5,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [26]:
torch.zeros((5,5), dtype = torch.int32)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [ ]:
# Returns a tensor filled with the scalar value 0, with the same size as input.
torch.zeros_like()

In [ ]:
# Returns a tensor filled with the scalar value 1, with the shape defined by the variable argument size.
torch.ones()
# Returns a tensor filled with the scalar value 1, with the same size as input.
torch.ones_like()

In [27]:
# Returns a 1-D tensor of size [(end-start)/step] with values from the interval [start, end) taken with common difference step 
# beginning from start.
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [28]:
torch.arange(0,5,2)

tensor([0, 2, 4])

In [30]:
# Returns a 1-D tensor of size [(end-start)/step]+1 with values from start to end with step step.
torch.range(0,5)

D:\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  


tensor([0., 1., 2., 3., 4., 5.])

In [31]:
for i in torch.arange(10):
    print("epoch:", i)

epoch: tensor(0)
epoch: tensor(1)
epoch: tensor(2)
epoch: tensor(3)
epoch: tensor(4)
epoch: tensor(5)
epoch: tensor(6)
epoch: tensor(7)
epoch: tensor(8)
epoch: tensor(9)


In [ ]:
# Creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end, inclusive.
torch.linspace()
# Creates a one-dimensional tensor of size steps whose values are evenly spaced from base^start to base^end, inclusive, 
# on a logarithmic scale with base base.
torch.logspace()

In [32]:
# Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [33]:
# Creates a tensor of size size filled with fill_value.
torch.full((2,2), 5)

tensor([[5, 5],
        [5, 5]])

In [ ]:
# Returns a tensor with the same size as input filled with full_value.
torch.full_like()

In [34]:
# Concatenates the givensequence of seq tensors in the given dimension.
a = torch.rand((2,2))
b = torch.rand((2,3))
torch.cat([a,b], dim = 1)

tensor([[0.3922, 0.4761, 0.9090, 0.5322, 0.9804],
        [0.9360, 0.7350, 0.4371, 0.7326, 0.6727]])

In [35]:
a = torch.rand((2,2))
b = torch.rand((3,2))
torch.cat([a,b], dim = 0)

tensor([[0.9257, 0.4181],
        [0.4269, 0.0657],
        [0.5864, 0.4321],
        [0.7378, 0.8758],
        [0.1813, 0.1989]])

In [ ]:
# Splits a tensor into a specific number of chunks. Each chunk is a view of the input tensor.
